import { StyleSheet } from "react-native";
import {
  BgNeutralInversePrimary,
  TextNeutralInversePrimary,
  TextNeutralInverseSecondary,
  BgNeutralInverseSecondary,
  BgNeutralInverseTertiary,
  BgSuccessBold,
  Brand5,
  LinkInverse,
  FontPrimary,
  FontWeightBlack,
  FontWeightBold,
  FontWeightRegular,
  FontWeightMedium,
  TypographyH3,
  TypographyH5,
  TypographyBodyMd,
  TypographyCaption,
  TypographyCaptionSm,
  FontSizeSm,
  Radius3xl,
  RadiusXl,
  RadiusFull,
  BorderWidthBase,
  Space1,
  Space2,
  Space3,
  Space4,
  Space6,
  Space8,
} from "@statrys/tokens";
import { nativeFontFamily } from "../nativeFont";

// Every value here is an existing shared token — no semantic/outstandingCard.json.
// The progress bar's gradient fill (gradient.badgeCustom, "fill" below) is
// approximated with a solid Brand5 on native — same "no new dependency"
// call as Badge's color="custom". `percent` label's 30px width has no
// matching token, so it's a plain literal.
export const styles = StyleSheet.create({
  card: {
    flexDirection: "column",
    gap: Space6,
    width: "100%",
    padding: Space8,
    borderRadius: Radius3xl,
    backgroundColor: BgNeutralInversePrimary,
  },
  headerRow: { flexDirection: "row", alignItems: "flex-start", gap: Space4 },
  headerText: { flex: 1, flexDirection: "column", gap: Space1 },
  label: {
    color: TextNeutralInversePrimary,
    fontFamily: nativeFontFamily(FontPrimary, FontWeightRegular),
    fontWeight: String(FontWeightRegular) as "400",
    fontSize: TypographyBodyMd,
    lineHeight: TypographyBodyMd * 1.3,
  },
  amountRow: { flexDirection: "row", alignItems: "flex-end", gap: Space2 },
  currency: {
    color: TextNeutralInversePrimary,
    fontFamily: nativeFontFamily(FontPrimary, FontWeightRegular),
    fontWeight: String(FontWeightRegular) as "400",
    fontSize: TypographyCaption,
    lineHeight: TypographyCaption * 1.3,
  },
  expected: {
    color: TextNeutralInversePrimary,
    fontFamily: nativeFontFamily(FontPrimary, FontWeightBlack),
    fontWeight: String(FontWeightBlack) as "800",
    fontSize: TypographyH3,
    lineHeight: TypographyH3,
    letterSpacing: -TypographyH3 * 0.05,
  },
  collected: {
    color: TextNeutralInversePrimary,
    fontFamily: nativeFontFamily(FontPrimary, FontWeightBold),
    fontWeight: String(FontWeightBold) as "700",
    fontSize: TypographyH5,
    lineHeight: TypographyH5,
    letterSpacing: -TypographyH5 * 0.05,
  },
  outstanding: {
    color: TextNeutralInversePrimary,
    fontFamily: nativeFontFamily(FontPrimary, FontWeightBold),
    fontWeight: String(FontWeightBold) as "700",
    fontSize: TypographyH5,
    lineHeight: TypographyH5,
    letterSpacing: -TypographyH5 * 0.05,
  },
  suffix: {
    color: TextNeutralInversePrimary,
    fontFamily: nativeFontFamily(FontPrimary, FontWeightRegular),
    fontWeight: String(FontWeightRegular) as "400",
    fontSize: TypographyCaption,
  },
  collectedBox: {
    flexDirection: "column",
    gap: Space2,
    width: "100%",
    padding: Space4,
    borderRadius: RadiusXl,
    backgroundColor: BgNeutralInverseSecondary,
  },
  boxLabel: {
    color: TextNeutralInverseSecondary,
    fontFamily: nativeFontFamily(FontPrimary, FontWeightMedium),
    fontWeight: String(FontWeightMedium) as "500",
    fontSize: TypographyCaption,
    lineHeight: TypographyCaption * 1.3,
  },
  barRow: { flexDirection: "row", alignItems: "center", gap: Space4, width: "100%" },
  track: { flex: 1, height: Space3, borderRadius: RadiusFull, backgroundColor: BgNeutralInverseTertiary, overflow: "hidden" },
  fill: { height: "100%", borderRadius: RadiusFull, backgroundColor: Brand5 },
  fillFull: { height: "100%", borderRadius: RadiusFull, backgroundColor: BgSuccessBold },
  percent: {
    width: 30,
    textAlign: "right",
    color: TextNeutralInversePrimary,
    fontFamily: nativeFontFamily(FontPrimary, FontWeightMedium),
    fontWeight: String(FontWeightMedium) as "500",
    fontSize: TypographyCaption,
    lineHeight: TypographyCaption * 1.3,
  },
  encouragement: { flexDirection: "row", alignItems: "center", gap: Space2 },
  encouragementText: {
    color: TextNeutralInversePrimary,
    fontFamily: nativeFontFamily(FontPrimary, FontWeightRegular),
    fontWeight: String(FontWeightRegular) as "400",
    fontSize: TypographyCaptionSm,
    lineHeight: TypographyCaptionSm * 1.3,
    letterSpacing: -0.5,
  },
  divider: { width: "100%", borderTopWidth: BorderWidthBase, borderTopColor: BgNeutralInverseTertiary },
  footer: { flexDirection: "row", alignItems: "flex-end", gap: Space8, width: "100%" },
  outstandingBlock: { flex: 1, flexDirection: "column", gap: Space1 },
  link: { flexDirection: "row", alignItems: "center", gap: Space2 },
  linkText: {
    color: LinkInverse,
    fontFamily: nativeFontFamily(FontPrimary, FontWeightMedium),
    fontWeight: String(FontWeightMedium) as "500",
    fontSize: FontSizeSm,
    lineHeight: FontSizeSm,
  },
});

export const INVERSE_TEXT_COLOR = TextNeutralInversePrimary;
export const LINK_COLOR = LinkInverse;
